#pragma once
#include <string>

#pragma pack(push, 1)
struct gameupdatepacket_t {
	uint8_t m_type;
	uint8_t m_netid;
	uint8_t m_jump_amount;
	uint8_t m_count;
	int32_t m_player_flags;
	int32_t m_item;
	int32_t m_packet_flags;
	float m_struct_flags;
	int32_t m_int_data;
	float m_vec_x;
	float m_vec_y;
	float m_vec2_x;
	float m_vec2_y;
	float m_particle_time;
	uint32_t m_state1;
	uint32_t m_state2;
	uint32_t m_data_size;
	uint32_t m_data;
};
typedef struct gametankpacket_t {
	int32_t m_type;
	char m_data;
} gametextpacket_t;
#pragma pack(pop)
enum {
	PACKET_STATE = 0,
	PACKET_CALL_FUNCTION = 1,
	PACKET_UPDATE_STATUS = 2,
	PACKET_TILE_CHANGE_REQUEST = 3,
	PACKET_SEND_MAP_DATA = 4,
	PACKET_SEND_TILE_UPDATE_DATA = 5,
	PACKET_SEND_TILE_UPDATE_DATA_MULTIPLE = 6,
	PACKET_TILE_ACTIVATE_REQUEST = 7,
	PACKET_TILE_APPLY_DAMAGE = 8,
	PACKET_SEND_INVENTORY_STATE = 9,
	PACKET_ITEM_ACTIVATE_REQUEST = 10,
	PACKET_ITEM_ACTIVATE_OBJECT_REQUEST = 11,
	PACKET_SEND_TILE_TREE_STATE = 12,
	PACKET_MODIFY_ITEM_INVENTORY = 13,
	PACKET_ITEM_CHANGE_OBJECT = 14,
	PACKET_SEND_LOCK = 15,
	PACKET_SEND_ITEM_DATABASE_DATA = 16,
	PACKET_SEND_PARTICLE_EFFECT = 17,
	PACKET_SET_ICON_STATE = 18,
	PACKET_ITEM_EFFECT = 19,
	PACKET_SET_CHARACTER_STATE = 20,
	PACKET_PING_REPLY = 21,
	PACKET_PING_REQUEST = 22,
	PACKET_GOT_PUNCHED = 23,
	PACKET_APP_CHECK_RESPONSE = 24,
	PACKET_APP_INTEGRITY_FAIL = 25,
	PACKET_DISCONNECT = 26,
	PACKET_BATTLE_JOIN = 27,
	PACKET_BATTLE_EVEN = 28,
	PACKET_USE_DOOR = 29,
	PACKET_SEND_PARENTAL = 30,
	PACKET_GONE_FISHIN = 31,
	PACKET_STEAM = 32,
	PACKET_PET_BATTLE = 33,
	PACKET_NPC = 34,
	PACKET_SPECIAL = 35,
	PACKET_SEND_PARTICLE_EFFECT_V2 = 36,
	GAME_ACTIVE_ARROW_TO_ITEM = 37,
	GAME_SELECT_TILE_INDEX = 38
};
enum {
	NET_MESSAGE_UNKNOWN = 0,
	NET_MESSAGE_SERVER_HELLO = 1,
	NET_MESSAGE_GENERIC_TEXT = 2,
	NET_MESSAGE_GAME_MESSAGE = 3,
	NET_MESSAGE_GAME_PACKET = 4,
	NET_MESSAGE_ERROR = 5,
	NET_MESSAGE_TRACK = 6,
	NET_MESSAGE_CLIENT_LOG_REQUEST = 7,
	NET_MESSAGE_CLIENT_LOG_RESPONSE = 8
};


enum {
	UPDATE_PACKET_FALLING_DOWN = 0,
	UPDATE_PACKET_TILE_CHANGE_REQUEST_RIGHT = 0,
	UPDATE_PACKET_TILE_CHANGE_REQUEST_LEFT = 16,
	UPDATE_PACKET_PLAYER_MOVING_RIGHT = 32,
	UPDATE_PACKET_PLAYER_MOVING_LEFT = 48,
	UPDATE_PACKET_PLAYER_JUMPING_RIGHT = 128,
	UPDATE_PACKET_PLAYER_JUMPING_LEFT = 144,
	UPDATE_PACKET_PLACE_BLOCK_RIGHT = 3104,
	UPDATE_PACKET_PLACE_BLOCK_LEFT = 3120,
	UPDATE_PACKET_PUNCH_TILE_RIGHT = 2592,
	UPDATE_PACKET_PUNCH_TILE_LEFT = 2608,
	UPDATE_PACKET_PICK_UP_OBJECT_RIGHT = 16416,
	UPDATE_PACKET_PICK_UP_OBJECT_LEFT = 16432
};